name: deploy
on:
  push:
    branches:
      - main
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: >-
          for page in `ls ./src/*.html`;
          do 
            sed -i "s|<link rel=\"stylesheet\" type=\"text/css\" href=\"./style.css\" />|<style>$(<./src/style.css sed -e 's/&/\\&/g' -e 's/\//\\\//g' | tr -d '\n')</style>|g" $page;
          done

      - run: >-
          for page in `ls ./src/*.html`;
          do 
            sed -i "s|<script src=\"script.js\"></script>|<script>$(<./src/script.js sed -e 's/&/\\&/g' -e 's/\//\\\//g' | tr -d '\n')</script>|g" $page;
          done

      - run: pip3 install pybtex
      - run: python3 ./tools/generate_bibliography.py
      - run: sed -i "s/<\!-- bibliography -->/$(<bibliography.html sed -e 's/&/\\&/g' -e 's/\//\\\//g' | tr -d '\n')/g" ./src/research.html
      - run: sed -i "s/<\!-- masterstudents -->/$(<master.html sed -e 's/&/\\&/g' -e 's/\//\\\//g' | tr -d '\n')/g" ./src/research.html

      - run: mkdir dist
      
      - run: npx minify src/index.html > dist/index.html
      - run: npx minify src/research.html > dist/research.html
      - run: npx minify src/projects.html > dist/projects.html

      - run: cp resume.pdf dist/
      - run: cp robots.txt dist/
      - run: cp -r public dist/
      - run: cp -r bibtex dist/

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }}" ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/stevenhicks.xyz/
